version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

